
		/**
		 * THIS FILE IS AUTOMATICALLY GENERATED BY index.js
		 * ANY CHANGES WILL BE OVERWRITTEN
		 */
		import _0 from '/home/x/cloud/projects/wedding/src/components/app.js';
import _1 from '/home/x/cloud/projects/wedding/src/components/app/menu.js';
import _2 from '/home/x/cloud/projects/wedding/src/components/app/pages/home.js';

		export var routes = {
			'/app' : _0,
'/app/menu' : _1,
'/app/pages/home' : _2,
		};
	