
			/**
			 * THIS FILE IS AUTOMATICALLY GENERATED BY index.js
			 * ANY CHANGES WILL BE OVERWRITTEN
			 */
			
				import _0 from '/home/x/cloud/projects/hula/src/components/todo.js';
			

				import _1 from '/home/x/cloud/projects/hula/src/components/todo/list.js';
			

			const tmp_routes = {};

			
				tmp_routes['/todo'] = _0;
			

				tmp_routes['/todo/list'] = _1;
			

			export var routes = tmp_routes;
		