
		/**
		 * THIS FILE IS AUTOMATICALLY GENERATED BY index.js
		 * ANY CHANGES WILL BE OVERWRITTEN
		 */
		import _0 from '/home/x/cloud/projects/hula/src/components/todo.js';
import _1 from '/home/x/cloud/projects/hula/src/components/todo/list.js';

		export var routes = {
			'/todo' : _0,
'/todo/list' : _1,
		};
	